preferred_syntax = :sass
http_path = '/'
css_dir = 'public/css'
sass_dir = 'sass'
images_dir = 'assets/images'
javascripts_dir = 'assets/js'
relative_assets = true
line_comments = true
# output_style = :compressed
